# Generated by Django 5.2.3 on 2025-07-10 03:56

import cloudinary.models
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('category', multiselectfield.db.fields.MultiSelectField(choices=[('POPULAR', 'Popular Brands'), ('NEW', 'New Arrivals'), ('SALE', 'Sale Items'), ('TRENDING', 'Trending'), ('CLASSIC', 'Classic Styles')], default=['POPULAR'], max_length=33)),
            ],
        ),
    ]
