# Generated by Django 5.2.3 on 2025-07-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsoleapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='category',
        ),
        migrations.AddField(
            model_name='shoe',
            name='categories',
            field=models.ManyToManyField(to='newsoleapp.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('POPULAR', 'Popular Brands'), ('NEW', 'New Arrivals'), ('SALE', 'Sale Items'), ('TRENDING', 'Trending'), ('CLASSIC', 'Classic Styles')], max_length=50, unique=True),
        ),
    ]
