# Generated by Django 5.2.3 on 2025-06-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsoleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('POPULAR', 'Popular Brands'), ('NEW', 'New Arrivals'), ('SALE', 'Sale Items'), ('CLASSIC', 'Classic Styles')], default='POPULAR', max_length=20),
        ),
    ]
