# Generated by Django 5.2.3 on 2025-06-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsoleapp', '0002_shoe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('POPULAR', 'Popular Brands'), ('NEW', 'New Arrivals'), ('SALE', 'Sale Items'), ('TRENDING', 'Trending'), ('CLASSIC', 'Classic Styles')], default='POPULAR', max_length=20),
        ),
    ]
