# Generated by Django 5.2.3 on 2025-07-21 01:50

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsoleapp', '0002_remove_shoe_category_shoe_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='shoe',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('POPULAR', 'Popular Brands'), ('NEW', 'New Arrivals'), ('SALE', 'Sale Items'), ('TRENDING', 'Trending'), ('CLASSIC', 'Classic Styles')], default=['POPULAR'], max_length=33),
        ),
    ]
