# Generated by Django 5.2.3 on 2025-07-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsoleapp', '0003_remove_shoe_categories_delete_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
