# Generated by Django 5.2.3 on 2025-06-14 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsoleapp', '0003_alter_shoe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
