# Generated by Django 5.2.3 on 2025-07-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsoleapp', '0005_alter_shoe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
