# Generated by Django 5.2.3 on 2025-07-21 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsoleapp', '0006_alter_shoe_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='slug',
        ),
    ]
