# Generated by Django 5.2.3 on 2025-07-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsoleapp', '0007_remove_shoe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='product_code',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
