# Generated by Django 5.2.3 on 2025-07-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsoleapp', '0008_shoe_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
