# Generated by Django 5.2.3 on 2025-07-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsoleapp', '0009_shoe_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactForm',
        ),
        migrations.AlterField(
            model_name='shoe',
            name='product_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
