# Generated by Django 5.2.3 on 2025-06-15 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsoleapp', '0011_alter_shoe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='image',
        ),
    ]
