# Generated by Django 5.2.3 on 2025-06-17 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsoleapp', '0012_remove_shoe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='price',
        ),
    ]
