# Generated by Django 5.2.3 on 2025-06-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsoleapp', '0013_remove_shoe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
