# Generated by Django 5.2.3 on 2025-06-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsoleapp', '0014_shoe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='image',
            field=models.ImageField(default='static/default_shoe.jpg', upload_to='static'),
        ),
    ]
